name: Deploy to Endora via SFTP

on:
  push:
    branches:
      - main # Change to your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          host: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: 22
          local_path: './*' # Uploads everything from repository root
          remote_path: '/web' # Replace with your web root folder on Endora (e.g. /web or /subdom/www)
          sftp_only: true
